# YCSB Workload E – Short ranges (scan)
# 95% short scans, 5% inserts.
# seekrandomwhilewriting: N-1 threads do Seek+Next, 1 thread writes.

benchmarks=seekrandomwhilewriting
seek_nexts=100
use_existing_db=1
